### ISSUE TITLE
URLs or text with links aren't clickable in the Lessons Plan Guide

### ISSUE THREAD

**Issue by MagicFab** [MyFirstBitcoin/Bitcoin-Diploma-2024#2]
None of the URLs for videos and references to outside web sites in [the Lesson plan guide](https://github.com/MyFirstBitcoin/Bitcoin-Diploma-2024/blob/main/Educators%20Lesson%20Plan/Lesson%20Plan%20Guide%20-%202024%20-.pdf) are clickable.

Unfortunately I can't fix this as the source files are in Adobe proprietary format instead of markup or at least ODF format.

**Comment by BabaevDaniel** [comment]
Noted. We will work on a fix.

**Comment by BabaevDaniel** [comment]
Reuploaded files and works as it should.
